[llm]
    [llm.ollama]
        base_url = "https://ollama.molodetz.nl/" # 'https://ollama.molodetz.nl/' or 'http://127.0.0.1:11434/'
        model = "gemma3:270m" # 'gpt-oss:20b', 'gemma3:270m'
        think = false # true, false

    [llm.openai]
        api_key = "$OPENAI_API_KEY"
        model = "o3"

    [llm.googleai]
        api_key = "$GOOGLEAI_API_KEY"
        backup_keys = "$GOOGLEAI_API_BACKUP_KEYS"
        model = "gemini-2.5-pro"

    [llm.custom_inference]
        model = "gpt-oss-gest-e2e" # '<PLACEHOLDER>-e2e' or '<PLACEHOLDER>-generation-only'

[gest]
    task = "evaluation" # "generation" or "evaluation"
    data_path = "/workspaces/GEST/data"
    manual_path = "/workspaces/GEST/data"
    blacklist_path = "/workspaces/GEST/data"
    [gest.engine]
        retries = 3
        delay = 0
        [gest.engine.generation]
            llm_provider = "custom_inference" # "ollama", "openai", "googleai" or "custom_inference"
            retries = 5
            delay = 0
            include_detailed_instructions = true # true, false
            include_few_shot_examples = false # true, false
        [gest.engine.improvement]
            llm_provider = "googleai" # "ollama", "openai" or "googleai"
            skip_improvement_step = false # true, false
            retries = 3
            delay = 0
            text_similarity_threshold = 0.9
            include_exact_no_sentences = true # true, false
            include_detailed_instructions = true # true, false
            include_few_shot_examples = true # true, false

    [gest.logging]
        level = "INFO"
        dir = "/workspaces/GEST/logs"

    [gest.templates]
        dir = "/workspaces/GEST/templates"

    [gest.alerts]
        enabled = false # true, false
        from_email = "$ALERTS_FROM_GMAIL_EMAIL"
        to_emails = "$ALERTS_TO_EMAILS"

[text_similarity]
    [text_similarity.models]
        cache_dir = "/workspaces/GEST/miscellaneous/.cache/text_similarity/models"
        model_name = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

[graph_matching]
    [graph_matching.embeddings]
        cache_dir = "/workspaces/GEST/miscellaneous/.cache/graph_matching/embeddings"

        [graph_matching.embeddings.glove50]
            model_name = "glove-wiki-gigaword-50"
            file_name = "glove.6B.zip"
            url = "https://huggingface.co/stanfordnlp/glove/resolve/main/glove.6B.zip"
            dim = 50

        [graph_matching.embeddings.glove300]
            model_name = "glove-wiki-gigaword-300"
            file_name = "glove.6B.zip"
            url = "https://huggingface.co/stanfordnlp/glove/resolve/main/glove.6B.zip"
            dim = 300

        [graph_matching.embeddings.w2v_google]
            model_name = "word2vec-google-news-300"
            file_name = "GoogleNews-vectors-negative300.bin"
            url = "https://figshare.com/ndownloader/files/10798046"
            dim = 300

[datetime]
    timezone = "Europe/Bucharest"
    format = "%Y-%m-%d %H:%M:%S"
